### ISSUE TITLE
Jasmine 2.x Support

### ISSUE THREAD

**Issue by Tecuya** [searls/jasmine-given#20]
Jasmine 2.x breaks the custom matcher API.  I've created a branch in a fork which works with the new API:

https://github.com/Tecuya/jasmine-given/tree/support-jasmine-2

**Comment by brp-nylin** [comment]
Is the master branch working together with Jasmine 2.0 atm?

**Comment by searls** [comment]
Yes

**Comment by brp-nylin** [comment]
Thank you for your answer.

**Comment by shairez** [comment]
@searls consider closing this?
