### ISSUE TITLE
TypeError: Object [object Object] has no method 'toHaveReturnedFalseFromThen'

### ISSUE THREAD

**Issue by galenp** [searls/jasmine-given#39]
Hello

I am attempting to write coffeescript protractor e2e tests using jasmine-given.

Things seem to work for the most part, the tests run and the form is filled in and submitted but the Then statement fails with an error. It seems to fail regardless of my test... 
## login_spec.coffee

``` coffee
describe 'login spec', ->
  LoginView = require('./views/view-login.js')
  view = new LoginView();

  describe 'when a user logs in with correct details', ->
    Given -> view.fillEmail("test@test.com")
    Given -> view.fillPassword()
    When -> view.login()
    Then -> expect(view.currentUserName).toBeDefined()
```
## top of protractor.conf

``` js
require('coffee-script/register');
require('jasmine-given');
```

And then it's a standard protractor conf.
## Results

``` sh
Failures:

  1) login spec when a user logs in with correct details then expect(view.currentUserName).toBeDefined()
   Message:
     TypeError: Object [object Object] has no method 'toHaveReturnedFalseFromThen'

Finished in 3.663 seconds
1 test, 1 assertion, 1 failure
```

I don't understand the error or what it could relate to. I've checked that toHaveReturnedFalseFromThen is part of jasmine-given.

Thanks in Advance

**Comment by marcelboettcher** [comment]
getting the same error with newest version 2.6.2, coffescript 1.7.1 and protractor 2.0.0

Did you find a solution, @galenp?

Thanks a lot!
Marcel
