### ISSUE TITLE
Issue with running tests inside a loop

### ISSUE THREAD

**Issue by Nighthawk14** [searls/jasmine-given#49]
Hi all! 

I'm currently updating a test codebase from jasmine 1 to 2 and that means using your helper instead of this one [jasmine-grammar](https://github.com/rudylattae/jasmine-species/blob/master/src/jasmine-species/jasmine-grammar.js) and I'm currently experiencing issues when tests are inside a loop (example below):

``` js
[
    {expectedVariable: 'foo'},
    {expectedVariable: 'bar'},
    {expectedVariable: 'quux'},
].forEach((scenario) => {
    it(`expect variable to be  ${scenario.expectedVariable}`, () => {
        Given(() => {
            sinon.stub(service, 'foo').returns(scenario.expectedVariable);
        });

        Then(() => {
            expect(service.bar()).toBe(scenario.expectedVariable);
        });
    });
});
```

The problem is that in this case, the third iteration of the loop will fail, with sinon saying that the property `foo` on the object `service` is already stubbed (same thing with a classic jasmine Spy). 
With the previous library jasmine-grammar the given / when / then methods were executed synchronously in the context of the spec. Although I don't know how that works in your code guys. Could you please help me find a way to fix that?

Thanks!

**Comment by searls** [comment]
Well, for starters, jasmine-given's methods are meant to be called inside an example group (e.g. `describe`) and not inside a spec (`it`), like you have there. `Given` roughly maps to `beforeEach` and `Then` to `it`.

Try deleting the `it`.

**Comment by Nighthawk14** [comment]
Thanks for the reply. 

I tried but it didn't solve it, if I extract the Given part from the loop it works though. That would be a really big change for us so I'm not sure that we can go with this solution :/.

**Comment by searls** [comment]
Roger that.
