### ISSUE TITLE
xit and fit variations for jasmine-given

### ISSUE THREAD

**Issue by niwrA** [searls/jasmine-given#52]
Hi,

I've been working with jasmine-given for a while now on a project that implemented this. It's a nice setup. I was wondering though if there is an equivalent for xit and fit in the library to select specific tests for running, or excluse specific tests from running.

If not, this would be a feature request. 

Kind regards,
Arwin

**Comment by searls** [comment]
If your version of jasmine 2.1 or later you can probably just do `xThen = fit` globally.

**Comment by niwrA** [comment]
xthen didn't work, but looking into the jasmine code I noticed xdescribe and fdescribe, which is probably the best solution anyway. Thanks for the hint.
