### ISSUE TITLE
Jest support

### ISSUE THREAD

**Issue by DmitryEfimenko** [searls/jasmine-given#54]
This is a question/feature request.
I know the package name is **jasmine-given** , not **jest-given** :D. However, I'm wondering if it'd be too much work to support Jest?

PS: There is a package named [jest-given](https://www.npmjs.com/package/jest-given), but it's completely different thing.

**Comment by csaszika** [comment]
thanks for creating this for jest:
https://www.npmjs.com/package/jest-given-when-then
